services:
  api:
    image: node:22-alpine
    container_name: crm-controlle-api
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3333:3333"
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
